TourDuLich/Models/Tour.cs
using System.ComponentModel.DataAnnotations;

namespace TourDuLich.Models
{
    public class Tour
    {
        public int Id { get; set; }
        public string Name { get; set; }
    
        public string MoTa { get; set; }
        public decimal GiaTour { get; set; }
        public DateTime NgayBatDau { get; set; }
        public DateTime NgayKetThuc { get; set; }
        public string DiemKhoiHanh { get; set; }
        public string DiemDen { get; set; }
        public string?  ImageUrl { get; set; }
        public List<Image>? Images { get; set; }
        public int LoaiTourId { get; set; }
        public LoaiTour? LoaiTour { get; set; }
        
    }

}

TourDuLich/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TourDuLich.Data;

namespace TourDuLich.Controllers
{
    public class BookingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookingController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult AddToCart(int tourId)
        {
            return View("AddToCart");
        }

        

    }


    
}

TourDuLich/Controllers/DatToursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TourDuLich.Data;
using TourDuLich.Models;

namespace TourDuLich.Controllers
{
    public class DatToursController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DatToursController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> AddToCartAsync(int tourId)
        {
            var applicationDbContext = _context.DatTours.Include(d => d.KhachHang).Include(d => d.Tour);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DatTours
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.DatTours.Include(d => d.KhachHang).Include(d => d.Tour);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DatTours/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datTour = await _context.DatTours
                .Include(d => d.KhachHang)
                .Include(d => d.Tour)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (datTour == null)
            {
                return NotFound();
            }

            return View(datTour);
        }

        // GET: DatTours/Create
        public IActionResult Create()
        {
            ViewData["KhachHangId"] = new SelectList(_context.KhachHangs, "Id", "Id");
            ViewData["TourId"] = new SelectList(_context.Tours, "Id", "Id");
            return View();
        }

        // POST: DatTours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,KhachHangId,TourId,NgayDat,NgayDi,NgayVe,SoNguoi,TongGia")] DatTour datTour)
        {
            if (ModelState.IsValid)
            {
                _context.Add(datTour);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KhachHangId"] = new SelectList(_context.KhachHangs, "Id", "Id", datTour.KhachHangId);
            ViewData["TourId"] = new SelectList(_context.Tours, "Id", "Id", datTour.TourId);
            return View(datTour);
        }

        // GET: DatTours/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datTour = await _context.DatTours.FindAsync(id);
            if (datTour == null)
            {
                return NotFound();
            }
            ViewData["KhachHangId"] = new SelectList(_context.KhachHangs, "Id", "Id", datTour.KhachHangId);
            ViewData["TourId"] = new SelectList(_context.Tours, "Id", "Id", datTour.TourId);
            return View(datTour);
        }

        // POST: DatTours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,KhachHangId,TourId,NgayDat,NgayDi,NgayVe,SoNguoi,TongGia")] DatTour datTour)
        {
            if (id != datTour.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(datTour);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DatTourExists(datTour.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KhachHangId"] = new SelectList(_context.KhachHangs, "Id", "Id", datTour.KhachHangId);
            ViewData["TourId"] = new SelectList(_context.Tours, "Id", "Id", datTour.TourId);
            return View(datTour);
        }

        // GET: DatTours/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datTour = await _context.DatTours
                .Include(d => d.KhachHang)
                .Include(d => d.Tour)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (datTour == null)
            {
                return NotFound();
            }

            return View(datTour);
        }

        // POST: DatTours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var datTour = await _context.DatTours.FindAsync(id);
            if (datTour != null)
            {
                _context.DatTours.Remove(datTour);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DatTourExists(int id)
        {
            return _context.DatTours.Any(e => e.Id == id);
        }
    }
}

TourDuLich/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TourDuLich.Data;
using TourDuLich.Models;

namespace TourDuLich.Controllers
{
    public class ToursController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ToursController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Tours
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tours.Include(t => t.LoaiTour);
            return View(await applicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> TourDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours
                .Include(t => t.LoaiTour)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tour == null)
            {
                return NotFound();
            }

            return View(tour);
        }


        // GET: Tours/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours
                .Include(t => t.LoaiTour)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tour == null)
            {
                return NotFound();
            }

            return View(tour);
        }

        // GET: Tours/Create
        public IActionResult Create()
        {
            ViewData["LoaiTourId"] = new SelectList(_context.LoaiTours, "Id", "Name");
            return View();
        }

        // POST: Tours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,MoTa,GiaTour,NgayBatDau,NgayKetThuc,DiemKhoiHanh,DiemDen,LoaiTourId")] Tour tour, IFormFile tourImage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (tourImage != null )
                    {
                        tour.ImageUrl = await SaveImage(tourImage); 
                    }
                    
                }
                _context.Add(tour);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                ViewData["LoaiTourId"] = new SelectList(_context.LoaiTours, "Id", "Name", tour.LoaiTourId);
                return View(tour);
            }
            catch (Exception ex)
            {
                // In thông báo lỗi ra Output Window trong Visual Studio
                System.Diagnostics.Debug.WriteLine(ex.Message);
                throw; // Ném lỗi để xem chi tiết trong cửa sổ Exceptions trong Visual Studio
            }
        }

        // GET: Tours/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours.FindAsync(id);
            if (tour == null)
            {
                return NotFound();
            }
            ViewData["LoaiTourId"] = new SelectList(_context.LoaiTours, "Id", "Name", tour.LoaiTourId);
            return View(tour);
        }

        // POST: Tours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,MoTa,GiaTour,NgayBatDau,NgayKetThuc,DiemKhoiHanh,DiemDen,ImageUrl,LoaiTourId")] Tour tour)
        {
            if (id != tour.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tour);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TourExists(tour.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaiTourId"] = new SelectList(_context.LoaiTours, "Id", "Name", tour.LoaiTourId);
            return View(tour);
        }

        // GET: Tours/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours
                .Include(t => t.LoaiTour)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tour == null)
            {
                return NotFound();
            }

            return View(tour);
        }

        // POST: Tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tour = await _context.Tours.FindAsync(id);
            if (tour != null)
            {
                _context.Tours.Remove(tour);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TourExists(int id)
        {
            return _context.Tours.Any(e => e.Id == id);
        }


        private async Task<string> SaveImage(IFormFile image)
        {
            var savePath = Path.Combine("wwwroot/img", image.FileName);
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return "/img/" + image.FileName;
        }
    }
}

TourDuLich/Views/Tours/Create.cshtml
@model TourDuLich.Models.Tour


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Tour</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaTour" class="control-label"></label>
                <input asp-for="GiaTour" class="form-control" />
                <span asp-validation-for="GiaTour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayBatDau" class="control-label"></label>
                <input asp-for="NgayBatDau" class="form-control" />
                <span asp-validation-for="NgayBatDau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayKetThuc" class="control-label"></label>
                <input asp-for="NgayKetThuc" class="form-control" />
                <span asp-validation-for="NgayKetThuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiemKhoiHanh" class="control-label"></label>
                <input asp-for="DiemKhoiHanh" class="form-control" />
                <span asp-validation-for="DiemKhoiHanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiemDen" class="control-label"></label>
                <input asp-for="DiemDen" class="form-control" />
                <span asp-validation-for="DiemDen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="ImageUrl">Tour Image</label>
                <input type="file" id="ImageUrl" name="ImageUrl" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="LoaiTourId" class="control-label"></label>
                <select asp-for="LoaiTourId" class ="form-control" asp-items="ViewBag.LoaiTourId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TourDuLich/Views/Tours/Delete.cshtml
@model TourDuLich.Models.Tour

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tour</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GiaTour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaTour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayBatDau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayBatDau)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayKetThuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiemKhoiHanh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemKhoiHanh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiemDen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemDen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoaiTour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoaiTour.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TourDuLich/Views/Tours/Details.cshtml
@model TourDuLich.Models.Tour

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Tour</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GiaTour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaTour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayBatDau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayBatDau)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayKetThuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiemKhoiHanh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemKhoiHanh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiemDen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemDen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoaiTour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoaiTour.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TourDuLich/Views/Tours/Edit.cshtml
@model TourDuLich.Models.Tour

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Tour</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaTour" class="control-label"></label>
                <input asp-for="GiaTour" class="form-control" />
                <span asp-validation-for="GiaTour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayBatDau" class="control-label"></label>
                <input asp-for="NgayBatDau" class="form-control" />
                <span asp-validation-for="NgayBatDau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayKetThuc" class="control-label"></label>
                <input asp-for="NgayKetThuc" class="form-control" />
                <span asp-validation-for="NgayKetThuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiemKhoiHanh" class="control-label"></label>
                <input asp-for="DiemKhoiHanh" class="form-control" />
                <span asp-validation-for="DiemKhoiHanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiemDen" class="control-label"></label>
                <input asp-for="DiemDen" class="form-control" />
                <span asp-validation-for="DiemDen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiTourId" class="control-label"></label>
                <select asp-for="LoaiTourId" class="form-control" asp-items="ViewBag.LoaiTourId"></select>
                <span asp-validation-for="LoaiTourId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TourDuLich/Views/Tours/TourByCategory.cshtml
@model IEnumerable<TourDuLich.Models.Tour>


@{
    ViewData["Title"] = "TourByCategory";
    Layout = "~/Views/Shared/_TourList.cshtml";
}

<div class="row g-4 justify-content-center">
    @foreach (var item in Model)
    {

        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="package-item">
                <div class="overflow-hidden">
                    <img src="@item.ImageUrl" class="card-img-top" alt="@item.ImageUrl" style="height:300px;">
                </div>
                <div class="d-flex border-bottom">
                    <small class="flex-fill text-center border-end py-2"><i class="fa fa-map-marker-alt text-primary me-2"></i>@item.DiemDen</small>
                    <small class="flex-fill text-center border-end py-2"><i class="fa fa-calendar-alt text-primary me-2"></i>@item.NgayBatDau</small>
                    @* <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>2 Person</small> *@
                </div>
                <div class="text-center p-4">
                    <h3 class="mx-3">@item.GiaTour.ToString("#,##0") Vnđ</h3>
                    <div class="mb-3">
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                        <small class="fa fa-star text-primary"></small>
                    </div>
                    <h5  class="card-title"><a>@item.Name</a></h5>
                    <div class="d-flex justify-content-center mb-2">
                        <a href="TourDetails?id=@item.Id" class="btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">
                            Read More</a>
                        <a asp-controller="Booking" asp-action="AddToCart" asp-route-tourId="@item.Id" class="btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Book Now</a>
                    </div>  
                </div>
            </div>

        </div>
    }





</div>

TourDuLich/Views/Tours/TourDetails.cshtml
@model TourDuLich.Models.Tour

@{
    ViewData["Title"] = "TourDetails";
    Layout = "~/Views/Shared/_DetailView.cshtml";
}


<div>
    <h4>Thông Tin Tour</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Tên Tour: 
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            <p>Hình ảnh</p>

        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageUrl" class="card-img-top" alt="@Model.ImageUrl" style="height:auto;">
        </dd>
        <dt class = "col-sm-2">
           Mô tả:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
       
        <dt class = "col-sm-2">
            Ngày Khởi Hành: 
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayBatDau)
        </dd>
        <dt class = "col-sm-2">
           Ngày Về: 
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>
        <dt class = "col-sm-2">
            Điểm Khởi Hành
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemKhoiHanh)
        </dd>
        <dt class = "col-sm-2">
            Điểm Đến
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemDen)
        </dd>
        

        <dt class="col-sm-2">
            Giá Tour:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GiaTour)
        </dd>
       
    </dl>
    <a class="btn btn-primary  px-4" asp-controller="DatTours" asp-action="AddToCart">Book Now</a>
</div>
<div>
    
    <a asp-controller="Home" asp-action="Home">Back to Home</a>
</div>